version: "3.8"

services:
  backend:
    image: ranadeep04/bookadoc-backend:latest
    container_name: backend
    env_file:
      - ./backend.env
    ports:
      - "5000:5000"
    networks:
      - bookadoc-network
    restart: always

  frontend:
    image: ranadeep04/bookadoc-frontend:latest
    container_name: frontend
    env_file:
      - ./frontend.env
    ports:
      - "5173:5173"
    networks:
      - bookadoc-network
    depends_on:
      - backend
    restart: always

  admin:
    image: ranadeep04/bookadoc-admin:latest
    container_name: admin
    env_file:
      - ./admin.env
    ports:
      - "5174:5174"
    networks:
      - bookadoc-network
    depends_on:
      - backend
    restart: always

networks:
  bookadoc-network:
    driver: bridge
